"""Build a demo project: a synthetic subject, reviewed QC, and one run per recipe.

The ten-minute path for someone who has just cloned this. No recordings, no
permissions to arrange, no waiting on a QC review: `python -m dbsspeech seed`
produces a project where every screen has something real in it.

Three things this is careful about.

It writes only inside the demo root, never into `data/` and never into the
repository's own `derivatives/` or `runs/`. A demo that pollutes the provenance
log with runs nobody performed is worse than no demo.

The subject goes through the real QC gate. Detection proposes flags, the seed
approves them under a reviewer literally named `demo`, and signs. Nothing here
switches the gate off, so what a new person sees is the workflow they will
actually use, and every approval in the demo project is attributable to a
reviewer who is obviously not a person.

The recording is synthetic and says so in every way it can. Its study id is
`demo01`, its stimulation artifacts and beta oscillation are planted at known
values, and the manifest notes say where they came from.
"""

from __future__ import annotations

import csv
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ROOT = REPO_ROOT / "demo"

STUDY_ID = "demo01"
SESSION = "ses1"
REVIEWER = "demo"
CONTACTS = ("1", "2a", "2b", "2c", "3a", "3b", "3c", "4")

# Fast enough for the planted resonance to be measured rather than guessed at.
# See tests/fixtures/make_tdt_fixture.py.
SFREQ_HZ = 8000.0

# The demo recording is longer than the four-second test fixture, because two
# recipes cannot run on four seconds at their real defaults. A comodulogram needs
# ten cycles of its slowest phase frequency inside one window, 2.5 s at 4 Hz, and
# an event-locked average needs ten trials. The alternative was to lower both
# floors until four seconds satisfied them, which would produce a demo that ran
# and taught a new lab member the wrong number for what either recipe needs.
DEMO_DURATION_S = 12.0

# Parameters chosen so each recipe has something to show on a four-second
# recording. They are demo values, not recommendations: the defaults are tuned
# for real recordings, which are minutes long.
DEMO_PARAMS: dict[str, dict[str, Any]] = {
    "psd_by_condition": {"fmax": 200.0, "sfreq_target_hz": SFREQ_HZ},
    # window_s matches epoch_s: frequency resolution is 1 / window_s and an
    # epoch cannot supply more resolution than its own length. Leaving window_s
    # at its 1.0 s default inside a 0.5 s epoch used to be accepted and silently
    # halved the resolution.
    "bandpower_contrast": {"sfreq_target_hz": SFREQ_HZ, "epoch_s": 0.5,
                           "window_s": 0.5},
    "tfr_onset": {"tmin": -0.25, "tmax": 0.75, "fmax": 120.0, "n_freqs": 12,
                  "sfreq_target_hz": 1000.0, "baseline_tmin": -0.25,
                  "baseline_tmax": -0.05},
    "pynm_features": {"sfreq_target_hz": 1000.0},
    "erna": {"stim_source": "amplitude_threshold", "stim_refractory_ms": 100.0,
             "blanking_ms": 5.0, "analysis_ms": 60.0, "min_peaks": 6},
    # The fixture carries one event store, `Cam1`, at 0.5 s intervals. The recipe
    # refuses to guess which marker to lock to, so the demo names it rather than
    # relying on there happening to be only one.
    # One montage, not all five. Both of these default to every scheme, which
    # is five comodulograms and five epoch stacks per derivation per condition,
    # and the demo exists to show the shape of a result rather than to compare
    # montages.
    "erp_epochs": {"event_label": "Cam1", "references": ["bipolar_vertical"]},
    # Decimated for speed. The phase and amplitude ranges are left at their
    # defaults, which is the point of making the demo recording long enough.
    "pac_modulation_index": {"sfreq_target_hz": 500.0,
                             "references": ["bipolar_vertical"]},
}

CLAIM = "demo run on synthetic data, for the ten-minute walkthrough"


@dataclass
class SeedResult:
    """What the seed did, so the caller can print it or assert on it."""

    root: Path
    study_id: str
    n_flags: int
    qc_status: str
    runs: dict[str, str]        # recipe -> run id
    failures: dict[str, str]    # recipe -> why

    @property
    def ok(self) -> bool:
        return not self.failures


def _write_csv(path: Path, header: list[str], rows: list[list[str]]) -> None:
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)


def write_manifest(manifest_dir: Path) -> None:
    """The demo subject's rows. Same ten invariants as any other subject."""
    manifest_dir.mkdir(parents=True, exist_ok=True)
    note = "synthetic; generated by dbsspeech seed"

    _write_csv(
        manifest_dir / "subjects.csv",
        ["study_id", "session", "hemisphere", "format", "root_relpath",
         "acquisition", "acquisition_date", "notes"],
        [[STUDY_ID, SESSION, "R", "tdt_mat", "block", "demo", "", note]],
    )
    _write_csv(
        manifest_dir / "streams.csv",
        ["study_id", "session", "stream", "n_channels", "sfreq_hz", "units",
         "role", "relpath", "notes"],
        [[STUDY_ID, SESSION, "neur", "8", str(SFREQ_HZ), "V", "neural", "", note]],
    )
    _write_csv(
        manifest_dir / "leads.csv",
        ["study_id", "session", "lead_id", "target", "hemisphere", "lead_model",
         "channel_first", "channel_last", "rotation_deg", "notes"],
        [[STUDY_ID, SESSION, "lead1", "stn", "R", "unknown_directional_1331",
          "1", "8", "0", note]],
    )
    _write_csv(
        manifest_dir / "channels.csv",
        ["study_id", "session", "stream", "ch_index", "ch_name", "region",
         "lead_id", "lead_contact", "site", "include", "exclude_reason"],
        [[STUDY_ID, SESSION, "neur", str(i + 1), f"c{i + 1}", "stn", "lead1",
          contact, "", "true", ""] for i, contact in enumerate(CONTACTS)],
    )
    # Two conditions so a contrast has something to contrast, and windows whose
    # provenance is honest: they were decided by this script, not measured.
    _write_csv(
        manifest_dir / "windows.csv",
        ["study_id", "session", "condition", "t_start_s", "t_end_s",
         "derived_from", "status", "notes"],
        # Not starting at 0.0 and not ending at the last sample, so a recipe that
        # asks for time either side of an onset has it. A window flush against
        # the start of a recording is a real situation, and the demo is not the
        # place to meet it for the first time.
        # Overt starts at 0.2 so it contains all seven planted stimulation
        # onsets, which run from 0.30 s to 3.30 s; ERNA needs six of them.
        [[STUDY_ID, SESSION, "overt", "0.2", "5.5", "synthetic", "in_use", note],
         [STUDY_ID, SESSION, "metro", "6.0", "11.5", "synthetic", "in_use", note]],
    )


def build_project(root: Path, overwrite: bool = False) -> Path:
    """Write the recording and the manifest under `root`. Returns the root."""
    from .demo_data import make_fixture

    root = Path(root)
    if root.exists() and any(root.iterdir()) and not overwrite:
        raise FileExistsError(
            f"{root} already has something in it. Pass --overwrite to replace it, "
            "or choose another --root. Refusing to write over what is there."
        )
    if root.exists() and overwrite:
        shutil.rmtree(root)
    root.mkdir(parents=True)

    # Stimulation is on, so the QC screen has real flags to review and the ERNA
    # recipe has a resonance to find. Both are the point of a demo.
    make_fixture(root / "data" / "block" / "synthetic_block.mat", erna=True,
                 sfreq_hz=SFREQ_HZ, duration_s=DEMO_DURATION_S)
    write_manifest(root / "manifest")
    return root


def seed(
    root: Path | None = None,
    overwrite: bool = False,
    log: Any = print,
) -> SeedResult:
    """Build the demo project, take it through QC, and run every recipe."""
    from .qc import decide_many, load_decisions, propose, save_decisions, sign
    from .qc.gate import status as qc_status
    from .recipes import available
    from .recipes import run as run_recipe

    root = Path(root or DEFAULT_ROOT)
    build_project(root, overwrite=overwrite)
    log(f"demo project at {root}")

    manifest_dir = root / "manifest"
    data_dir = root / "data"
    derivatives = root / "derivatives"
    runs_dir = root / "runs"

    flags = _detect(manifest_dir, data_dir)
    propose(flags, STUDY_ID, derivatives)
    log(f"QC detection proposed {len(flags)} flag(s)")

    # Approved under a reviewer named `demo`, through the same functions the
    # review screen calls, so the decisions table shows what a real review
    # produces rather than an empty screen.
    #
    # Not blanket approval, because blanket approval is the wrong answer here and
    # the demo would be teaching it. Detection flags the two stimulating contacts
    # as kurtosis outliers and proposes excluding them, which is correct about
    # the statistic and wrong about what to do: the peakedness is the stimulation
    # artifact, and on a stimulation recording that artifact is the reason the
    # recording exists. Excluding those contacts would delete the ERNA. So they
    # are approved as real, with the action changed to none and a reason, which
    # is also the path a reviewer disagreeing with a proposal takes.
    rows = load_decisions(STUDY_ID, derivatives)
    keep, ordinary = _split_decisions(rows)
    if ordinary:
        rows = decide_many(
            rows, ordinary, approved=True, reviewer=REVIEWER,
            reason="demo data; approved so the walkthrough has something to show",
        )
    if keep:
        rows = decide_many(
            rows, keep, approved=True, reviewer=REVIEWER, action_taken="none",
            reason="the peakedness is the stimulation artifact, which is the "
                   "signal this recording was made for. Flag is real; excluding "
                   "the contact would delete the response. The recipe blanks it.",
        )
        log(f"kept {len(keep)} stimulating contact(s) that detection proposed excluding")
    save_decisions(STUDY_ID, rows, derivatives)
    sign(STUDY_ID, REVIEWER, derivatives)
    status = qc_status(STUDY_ID, derivatives)
    log(f"QC signed by {REVIEWER}; status {status}")

    runs: dict[str, str] = {}
    failures: dict[str, str] = {}
    for name in available():
        try:
            run_id = run_recipe(
                name, STUDY_ID, SESSION, claim=CLAIM,
                params=DEMO_PARAMS.get(name, {}), user=REVIEWER,
                manifest_dir=manifest_dir, data_dir=data_dir,
                runs_dir=runs_dir, derivatives_dir=derivatives,
            )
            runs[name] = run_id
            log(f"  {name}: {run_id}")
        except Exception as exc:  # noqa: BLE001 - reported, not raised
            failures[name] = f"{type(exc).__name__}: {exc}"
            log(f"  {name}: FAILED {failures[name]}")

    return SeedResult(root=root, study_id=STUDY_ID, n_flags=len(flags),
                      qc_status=status, runs=runs, failures=failures)


def _split_decisions(rows: list[dict[str, str]]) -> tuple[list[str], list[str]]:
    """Flag ids to approve as proposed, and ones whose contact must be kept.

    The second list is a proposal to exclude a contact that carries the planted
    stimulation response. Matched on the target, not the flag type, because what
    matters is which contact would be lost.
    """
    from .demo_data import ERNA_CHANNELS

    stimulating = {f"lead1:{CONTACTS[i]}" for i in ERNA_CHANNELS}
    keep, ordinary = [], []
    for row in rows:
        action = row.get("action_taken") or row.get("proposed_action", "")
        if action == "exclude_channel" and row.get("target") in stimulating:
            keep.append(row["flag_id"])
        else:
            ordinary.append(row["flag_id"])
    return keep, ordinary


def _detect(manifest_dir: Path, data_dir: Path) -> list:
    """Run the real QC detectors over the demo recording.

    Monopolar, like the CLI does, because QC judges the channels as recorded: a
    bad contact is a bad contact under any montage.
    """
    import numpy as np

    from .io.loader import open_session
    from .manifest import load_configs, load_manifest
    from .qc import detect_all

    configs = load_configs()
    thresholds = configs["qc_thresholds"]
    leads_cfg = configs["leads"]["leads"]
    manifest = load_manifest(manifest_dir)

    with open_session(STUDY_ID, SESSION, manifest=manifest, configs=configs,
                      data_dir=data_dir) as session:
        names, regions, kinds, chunks = [], [], [], []
        sfreq = 0.0
        for lead_id, lead in session.leads().items():
            sig = session.read_derived(lead_id, "monopolar", sfreq_target_hz=2034.5)
            by_id = {
                str(c["id"]): c.get("kind", "ring")
                for c in leads_cfg[lead.lead_model]["contacts"]
            }
            chunks.append(sig.data)
            names += [f"{lead_id}:{n}" for n in sig.names]
            regions += [lead.target] * len(sig.names)
            kinds += [by_id.get(n, "") for n in sig.names]
            sfreq = sig.sfreq_hz
        data = np.vstack(chunks)
    return detect_all(data, sfreq, names, regions, thresholds, kinds=kinds)
